"""add event indexes

Revision ID: 406063f3b39a
Revises: fc55c0538932
Create Date: 2026-06-27 12:53:22.866121
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '406063f3b39a'
down_revision: str | None = 'fc55c0538932'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_expires_at', 'events', ['expires_at'], unique=False)
    op.create_index('ix_events_geo', 'events', ['lat', 'lng'], unique=False)
    op.create_index('ix_events_start_time', 'events', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_start_time', table_name='events')
    op.drop_index('ix_events_geo', table_name='events')
    op.drop_index('ix_events_expires_at', table_name='events')
    # ### end Alembic commands ###
