"""add created_by to events

Revision ID: 6ead541c12d8
Revises: 406063f3b39a
Create Date: 2026-06-27 18:38:17.675544
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6ead541c12d8'
down_revision: str | None = '406063f3b39a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'created_by')
    # ### end Alembic commands ###
